# version param is deprecated
name: malanka-academy

services:
  postgres:
    image: postgres:15-alpine
    container_name: malanka-academy-postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: malanka_academy
      POSTGRES_PASSWORD: malanka_academy
      POSTGRES_DB: malanka_academy
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U malanka_academy" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres-data: { }
