spring:
  application:
    name: malanka-academy
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:malanka_academy}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:jwt/public-key.pem

application:
  security:
    access-token:
      expiry-in-seconds: ${ACCESS_TOKEN_EXPIRY:300}
    private-key: ${RSA_PRIVATE_KEY}
