---
name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    paths: [ src/** ]
    types: [ opened, synchronize ]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4

      - name: Set up JDK 21
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 #v4
        with:
          java-version: 21
          distribution: temurin

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 #v4

      - name: Build with Gradle Wrapper
        run: ./gradlew bootJar

      - name: Upload Artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 #v4
        with:
          path: ./build/libs/
          name: executable-jar
          if-no-files-found: error
          retention-days: 1

  test:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4

      - name: Set up JDK 21
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 #v4
        with:
          java-version: 21
          distribution: temurin

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 #v4

      - name: Test with Gradle Wrapper
        run: ./gradlew check

      - name: Upload Artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 #v4
        with:
          path: .
          overwrite: true
          name: ${{ github.event.repository.name }}
          if-no-files-found: error
          retention-days: 1
